### PR TITLE
rfc3392: outline

### PR DESCRIPTION
**Pull request by weihanglo**
Some terms may need more attentions:

- Accountability — ~~究責~~ 問責
- Audit — 稽核
- Backlog — 待辦事項
- Contingent Moderator — ~~非常設仲裁人~~ 仲裁人代表團
- Council — 理事會
- Moderate — 仲裁

### CODE REVIEW

**Comment by dieterplex** [comment]
“究責” is more like a verb.
I think it’s better to use “問責” like here:
https://www.learnwithkak.com/accountable-accountability-%E4%B8%AD%E6%96%87%E6%84%8F%E6%80%9D/
Also a book named “當責”: 
https://www.managertoday.com.tw/articles/view/1932

**Comment by weihanglo** [comment]
@dieterplex, just updated. WDYT?

**Comment by dieterplex** [comment]
LGTM overall. I'm not familiar to this kind of doc though :smile:

**Comment by CYBAI** [comment]
> Contingent Moderator — 非常設仲裁人

I don't fully understand "contingent" and the translated `非常設` though, with checking its [meaning on Yahoo Dictionary](https://tw.dictionary.search.yahoo.com/search?p=contingent), I wonder if `仲裁人代表團` would be easier to understand? 🤔 WDYT?

**Review by CYBAI — APPROVED** [review]
THANK YOU! Mostly LGTM but one nit at https://github.com/rust-tw/rfcs-tw/pull/33#issuecomment-1445281065.

**Comment by weihanglo** [comment]
Going to merge this and announce a call-for-translating in [Rust Taiwan Telegram Group](https://t.me/rust_tw). Thank you all!

**Pull request merged**
